// SPDX-FileCopyrightText: 2021-2026 sgawarat <sgawarat@gmail.com>
// SPDX-License-Identifier: GPL-2.0-or-later

/**
 * @file keyboard.h
 * @brief JIS配列
 */
#pragma once

#include <keymap.h>

#include <keymap_japanese.h>
#include <quantum_keycodes.h>

/* clang-format off */

/**
 * @brief キーマップレイヤーを定義するための便利マクロ
 */
#define LAYOUT( \
  ESCAPE, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, PRINT_SCREEN, SCROLL_LOCK, PAUSE, \
  HANKAKU_ZENKAKU, _1, _2, _3, _4, _5, _6, _7, _8, _9, _0, MINUS, CIRCUMFLEX, YEN, BACKSPACE, INSERT, HOME, PAGE_UP, NUM_LOCK, KP_SLASH, KP_ASTERISK, KP_MINUS, \
  TAB, Q, W, E, R, T, Y, U, I, O, P, AT, LEFT_BRACKET, DELETE, END, PAGE_DOWN, KP_7, KP_8, KP_9, \
  CAPS_LOCK, A, S, D, F, G, H, J, K, L, SEMICOLON, COLON, RIGHT_BRACKET, ENTER, KP_4, KP_5, KP_6, KP_PLUS, \
  LEFT_SHIFT, Z, X, C, V, B, N, M, COMMA, DOT, SLASH, BACKSLASH, RIGHT_SHIFT, UP, KP_1, KP_2, KP_3, \
  LEFT_CTRL, LEFT_GUI, LEFT_ALT, MUHENKAN, SPACE, HENKAN, KATAKANA_HIRAGANA, RIGHT_ALT, RIGHT_GUI, APPLICATION, RIGHT_CTRL, LEFT, DOWN, RIGHT, KP_0, KP_DOT, KP_ENTER \
) { \
  {ESCAPE, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, PRINT_SCREEN, SCROLL_LOCK, PAUSE}, \
  {HANKAKU_ZENKAKU, _1, _2, _3, _4, _5, _6, _7, _8, _9, _0, MINUS, CIRCUMFLEX, YEN, BACKSPACE, INSERT, HOME, PAGE_UP, NUM_LOCK, KP_SLASH, KP_ASTERISK, KP_MINUS}, \
  {TAB, Q, W, E, R, T, Y, U, I, O, P, AT, LEFT_BRACKET, DELETE, END, PAGE_DOWN, KP_7, KP_8, KP_9}, \
  {CAPS_LOCK, A, S, D, F, G, H, J, K, L, SEMICOLON, COLON, RIGHT_BRACKET, ENTER, KP_4, KP_5, KP_6, KP_PLUS}, \
  {LEFT_SHIFT, Z, X, C, V, B, N, M, COMMA, DOT, SLASH, BACKSLASH, RIGHT_SHIFT, UP, KP_1, KP_2, KP_3}, \
  {LEFT_CTRL, LEFT_GUI, LEFT_ALT, MUHENKAN, SPACE, HENKAN, KATAKANA_HIRAGANA, RIGHT_ALT, RIGHT_GUI, APPLICATION, RIGHT_CTRL, LEFT, DOWN, RIGHT, KP_0, KP_DOT, KP_ENTER}, \
}

/**
 * @brief キーマップレイヤーを定義するための便利マクロ
 * 
 * keychron/v6/isoの配列をJIS配列として流用できるようにするためのもの。
 * NUBS,F13,F14,F15,F16がバックスラッシュ、無変換、変換、カナ、円マークとして扱われる。
 */
#define LAYOUT_v6_iso( \
  ESCAPE, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, PRINT_SCREEN, SCROLL_LOCK, PAUSE, MUHENKAN, HENKAN, KATAKANA_HIRAGANA, YEN, \
  HANKAKU_ZENKAKU, _1, _2, _3, _4, _5, _6, _7, _8, _9, _0, MINUS, CIRCUMFLEX, BACKSPACE, INSERT, HOME, PAGE_UP, NUM_LOCK, KP_SLASH, KP_ASTERISK, KP_MINUS, \
  TAB, Q, W, E, R, T, Y, U, I, O, P, AT, LEFT_BRACKET, DELETE, END, PAGE_DOWN, KP_7, KP_8, KP_9, \
  CAPS_LOCK, A, S, D, F, G, H, J, K, L, SEMICOLON, COLON, RIGHT_BRACKET, ENTER, KP_4, KP_5, KP_6, KP_PLUS, \
  LEFT_SHIFT, BACKSLASH, Z, X, C, V, B, N, M, COMMA, DOT, SLASH, RIGHT_SHIFT, UP, KP_1, KP_2, KP_3, \
  LEFT_CTRL, LEFT_GUI, LEFT_ALT, SPACE, RIGHT_ALT, RIGHT_GUI, APPLICATION, RIGHT_CTRL, LEFT, DOWN, RIGHT, KP_0, KP_DOT, KP_ENTER \
) { \
  {ESCAPE, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, PRINT_SCREEN, SCROLL_LOCK, PAUSE}, \
  {HANKAKU_ZENKAKU, _1, _2, _3, _4, _5, _6, _7, _8, _9, _0, MINUS, CIRCUMFLEX, YEN, BACKSPACE, INSERT, HOME, PAGE_UP, NUM_LOCK, KP_SLASH, KP_ASTERISK, KP_MINUS}, \
  {TAB, Q, W, E, R, T, Y, U, I, O, P, AT, LEFT_BRACKET, DELETE, END, PAGE_DOWN, KP_7, KP_8, KP_9}, \
  {CAPS_LOCK, A, S, D, F, G, H, J, K, L, SEMICOLON, COLON, RIGHT_BRACKET, ENTER, KP_4, KP_5, KP_6, KP_PLUS}, \
  {LEFT_SHIFT, Z, X, C, V, B, N, M, COMMA, DOT, SLASH, BACKSLASH, RIGHT_SHIFT, UP, KP_1, KP_2, KP_3}, \
  {LEFT_CTRL, LEFT_GUI, LEFT_ALT, MUHENKAN, SPACE, HENKAN, KATAKANA_HIRAGANA, RIGHT_ALT, RIGHT_GUI, APPLICATION, RIGHT_CTRL, LEFT, DOWN, RIGHT, KP_0, KP_DOT, KP_ENTER}, \
}
/* clang-format on */
